version: 2.1

orbs:
  windows: circleci/windows@2.3.0

jobs:
  build_test:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing Build System
          command: 'apt-get update && apt-get install -y git build-essential libboost-system-dev cmake python2.7'
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Creating Build Files
          command: 'cd svgnative && cmake -Bbuild/linux -H.'
      - run:
          name: Creating Binary Files
          command: 'cd svgnative && cmake --build build/linux'
      - run:
          name: Run tests
          command: 'cd svgnative && /usr/bin/python2.7 script/runTest.py --test=test'
  build_with_clang:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing Build System
          command: 'apt-get update && apt-get install -y git build-essential libboost-system-dev clang cmake python2.7'
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Creating Build Files
          command: 'cd svgnative && cmake -Bbuild/linux -H. -DCMAKE_CXX_COMPILER=clang -DLIB_ONLY=ON'
      - run:
          name: Creating Binary Files
          command: 'cd svgnative && cmake --build build/linux'
  build_with_style_support:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing Build System
          command: 'apt-get update && apt-get install -y git build-essential libboost-system-dev cmake python2.7'
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Creating Build Files
          command: 'cd svgnative && cmake -Bbuild/linux -H. -DSTYLE=ON'
      - run:
          name: Creating Binary Files
          command: 'cd svgnative && cmake --build build/linux'
  build_with_cocoa:
    macos:
      xcode: "10.3.0"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Installing dependencies
          command: HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew install cmake boost
      - run:
          name: Creating Build Files
          command: 'cd svgnative && cmake -Bbuild/mac -H. -DCG=ON'
      - run:
          name: Creating Binary Files
          command: 'cd svgnative && cmake --build build/mac'
  build_with_win:
    executor: windows/default
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Installing CMake
          command: |
            $global:ProgressPreference = 'SilentlyContinue'
            $cmakeVersion = "3.16.2"
            $url = "https://github.com/Kitware/CMake/releases/download/v" + $cmakeVersion + "/cmake-" + $cmakeVersion + "-win64-x64.zip"
            $outputDir = (Get-Item -Path ".\").FullName
            $outputZip = $outputDir + "\cmake.zip"
            (New-Object System.Net.WebClient).DownloadFile($url, $outputZip)
            Expand-Archive -LiteralPath $outputZip -DestinationPath $outputDir -Force
      - run:
          name: Installing Boost
          command: |
            $global:ProgressPreference = 'SilentlyContinue'
            $url = "https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.zip"
            $outputDir = (Get-Item -Path ".\").FullName
            $outputZip = $outputDir + "\boost_1_72_0.zip"
            (New-Object System.Net.WebClient).DownloadFile($url, $outputZip)
            Expand-Archive -LiteralPath $outputZip -DestinationPath $outputDir -Force
      - run:
          name: Creating Build Files
          command: |
            $boostDir = (Get-Item -Path ".\").FullName + "\boost_1_72_0\"
            $env:BOOST_INCLUDEDIR = $boostDir
            $env:BOOST_ROOT = $boostDir + "boost"
            $cmakeVersion = "3.16.2"
            $env:Path += ";" + (Get-Item -Path ".\").FullName + "\cmake-" + $cmakeVersion + "-win64-x64\bin"
            cd .\svgnative
            cmake -Bbuild/win . -G "Visual Studio 16 2019"
      - run:
          name: Creating Binary Files
          command: |
            $boostDir = (Get-Item -Path ".\").FullName + "\boost_1_72_0\"
            $env:BOOST_INCLUDEDIR = $boostDir
            $env:BOOST_ROOT = $boostDir + "boost"
            $cmakeVersion = "3.16.2"
            $env:Path += ";" + (Get-Item -Path ".\").FullName + "\cmake-" + $cmakeVersion + "-win64-x64\bin"
            cd .\svgnative
            cmake --build build/win
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test
      - build_with_style_support
      - build_with_clang
      - build_with_cocoa
      - build_with_win
