version: 2

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing Build System
          command: 'apt-get update && apt-get install -y git build-essential libboost-system-dev cmake python2.7'
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Creating Build Files
          command: 'cd svgnative && cmake -Bbuild/linux -H.'
      - run:
          name: Creating Binary Files
          command: 'cd svgnative && cmake --build build/linux'
      - run:
          name: Run tests
          command: 'cd svgnative && /usr/bin/python2.7 script/runTest.py --test=test'
